name: pangeo
channels:
 - pytorch
 - pytorch3d
 - fvcore
 - bottler
 - iopath
 - conda-forge
dependencies:
 - python=3.9*
 - pangeo-notebook=2022.01.18
 - pip=20
 - adlfs
 - aesara>=2.3.2
 - arviz>=0.11.4
 - awscli
 - astropy
 - bottleneck
 - boto3
 - black
 - cartopy >= 0.20.0
 - cfgrib
 - cmip6_preprocessing
 - ciso
 - dask-ml
 - dask-jobqueue
 - dask-image
 - datashader
 - descartes
 - earthengine-api
 - earthdata
 - einops
 - eofs
 - erddapy
 - esmpy
 - fastjmd95
 - fsspec
 - fvcore
 - gcm_filters
 - kerchunk
 - flake8
 - gcsfs
 - gh
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - git-lfs
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - imageio
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - iopath::iopath
 - ipyleaflet
 - ipytree
 - ipywidgets
 - isort
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - lxml
 - lz4
 - libgpuarray
 - matplotlib-base
 - metpy
 - mkl
 - mkl-service
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - numcodecs
 - numpy
 - opencv
 - parse
 - pandas
 - panel
 - pillow
 - parcels
 - param!=1.11.0
 - plotly
 - prefect
 - pyarrow
 - pyfftw
 - pycamhd
 - pycuda
 - pydap
 - pyhdf
 - pyinterp
 - pymc3
 - pygeos
 - pygpu
 - pysolar
 - pystac
 - pystac-client
 - pytables
 - python-blosc
 - python-gist
 - python-graphviz
 - python-dateutil>=2.8.2
 - pytorch::pytorch
 - pytorch3d::pytorch3d
 - pytorch::torchvision
 - pytorch::torchaudio
 - pytorch::cudatoolkit=11.3
 - bottler::nvidiacub
 - pytz
 - pytmd
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - rise
 - s3fs>0.5
# - sat-search
# - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - shapely
 - skyfield
 - sparse
#  - stackstac 
 - sympy
 - pytables
 - tensorboard
 - tiledb-py
 - timezonefinder
 - torchinfo
 - utide
 - umap-learn
 - xarray
 - xarrayutils
 - xarray_leaflet
 - xarray-spatial
 - xcape
#  - xcube
 - xesmf
 - xgcm
 - xhistogram
 - xlayers
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - zarr
