name: pangeo
channels:
 - conda-forge
 - pytorch
 - pytorch3d
 - fvcore
 - bottler
 - nvidia
 - iopath
dependencies:
 - python=3.8*
 - pangeo-notebook=2021.09.30
 - pip=20
 - adlfs
 - awscli
 - astropy
 - bottleneck
 - boto3
 - black
 - cartopy >= 0.20.0
 - cfgrib
 - cmip6_preprocessing
 - ciso
 - dask-ml
 - dask-jobqueue
 - dask-image
 - datashader
 - descartes
 - earthengine-api
 - eofs
 - erddapy
 - esmpy
 - fastjmd95
 - fsspec
 - kerchunk
 - flake8
 - gcsfs
 - gh
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - imageio
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - iopath
 - ipyleaflet
 - ipywidgets
 - isort
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - lz4
 - matplotlib-base
 - metpy
 - mkl
 - mkl-service
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - numcodecs
 - numpy
 - opencv
 - pandas
 - panel
 - pillow
 - parcels
 - param!=1.11.0
 - plotly
 - prefect
 - pyarrow
 - pycamhd
 - pydap
 - pyhdf
 - pyinterp
 - pymc3
 - pygeos
 - pystac
 - python-blosc
 - python-gist
 - python-graphviz
 - pytorch
 - pytorch3d
 - torchvision
 - nvidia/label/cuda-11.4.2::cuda-toolkit
 - nvidiacub
 - pytz
 - pytmd
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - s3fs>0.5
 - sat-search
 - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - shapely
 - skyfield
 - sparse
 - stackstac 
 - sympy
 - pytables
 - theano-pymc
 - tiledb-py
 - timezonefinder
 - umap-learn
 - utide
 - xarray
 - xarrayutils
 - xarray_leaflet
 - xarray-spatial
 - xcape
 - xcube
 - xesmf
 - xgcm
 - xhistogram
 - xlayers
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - zarr
