name: pangeo
channels:
 - conda-forge
dependencies:
 - python=3.9*
 - pangeo-notebook=2022.01.18
 - pip=20
 - adlfs
 - awscli
 - astropy
 - bottleneck
 - boto3
 - bottleneck
 - cartopy >= 0.20.0
 - cfgrib
 - cmip6_preprocessing
 - ciso
 - dask-ml
 - dask-jobqueue
 - datashader
 - descartes
 - earthengine-api
 - earthdata
 - eofs
 - erddapy
 - esmpy
 - fastjmd95
 - fsspec
 - gcm_filters
 - gcsfs
 - gh
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - git-lfs
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipyleaflet
 - ipytree
 - ipywidgets
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - kerchunk
 - lxml
 - lz4
 - matplotlib-base
 - metpy
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - nomkl
 - numcodecs
 - numpy
 - pandas
 - panel
 - pillow
 - parcels
 - param!=1.11.0
 - prefect
 - pyarrow
 - pycamhd
 - pydap
 - pyhdf
 - pymc3
 - pygeos
 - pystac
 - pystac-client
 - pytables
 - python-blosc
 - python-gist
 - python-graphviz
 - pytz
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - rise
 - s3fs>0.5
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - shapely
 - skyfield
 - sparse
 - sympy
 # NOTE: waiting on https://github.com/gjoseph92/stackstac/issues/83
 # - stackstac
 - tiledb-py
 - timezonefinder
 - utide
 - umap-learn
 - xarray
 - xarrayutils
 - xarray_leaflet
 - xarray-spatial
 - xcape
 # - xcube>=0.9.1
 - xesmf
 - xgcm
 - xhistogram
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - zarr
