name: pangeo
channels:
 - conda-forge
dependencies:
 - python=3.8*
 - pangeo-notebook=2021.02.07
 - pip=20
 - adlfs
 - awscli
 - astropy
 - bottleneck
 - boto3
 - bottleneck
 - cartopy
 - cfgrib
 - cmip6_preprocessing
 - ciso
 - dask-ml
 - datashader
 - descartes
 - earthengine-api
 - eofs
 - erddapy
 - esmpy
 - fastjmd95
 - fsspec
 - gcsfs
 - geocube
 - geopandas
 - geoviews-core
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipyleaflet
 - ipywidgets
 - jupyter-panel-proxy
 - lz4
 - matplotlib-base
 - metpy
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - nomkl
 - numcodecs
 - numpy
 - pandas
 - panel
 - pillow
 - parcels
 - prefect
 - pyarrow
 - pycamhd
 - pydap
 - pymc3
 - pystac
 - python-blosc
 - python-gist
 - python-graphviz
 - pytz
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - s3fs>0.5
 - sat-search
 - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - shapely
 - skyfield
 - sparse
 - sympy
 - pytables
 - tiledb-py
 - utide
 - umap-learn
 - xarray
 - xarrayutils
 - xarray_leaflet
 - xarray-spatial
 - xcape
 - xcube
 - xesmf
 - xgcm
 - xhistogram
 - xlayers
 - xmitgcm
 - xpublish
 - xrft
 - zarr
